# Section Headings for the Front Page and Navbar
#-------------------------------------------------------------------------------
section-1: Section 1
section-2: Section 2
section-3: Section 3
section-4: Section 4

# Images
# ------------------------------------------------------------------------------
# Used for a full-width background image (roughly 2000 x 1333 pixels) on front page
frontpage-lead-image: assets/images/large-images/main-bg.jpg

#
first-image: assets/images/medium-images/front-1.jpg

#
about-1-image: assets/images/medium-images/about-1.jpg

#
about-2-image: assets/images/medium-images/about-2.jpg

# Header Options
# ------------------------------------------------------------------------------
# header-option: 1 # fixed header, transparent background, all caps, full-width image, centred text
header-option: 2 # fixed header, brand colour background, full-width image with centred text box
#header-option: 3 # traditional header, not fixed, logo location: assets/images/site-logo.png

# Front Page Intro Option
# ------------------------------------------------------------------------------
intro-section: "full-width-2"

header-logo: assets/images/logo.png

# Home Page Layout Options
# ------------------------------------------------------------------------------
#
# Layout of services on the home page: Choose "half", "quarter" or "third"
service-layout: "half"

# Add a slider to the first section
section-1-slider: false

# If you'd like to include the "Team" section on the front page, set this value to true.
# If you're including team, you can set values in _data/people.json or _data/people.csv
team: false

# Contact Page Layout Options
# ------------------------------------------------------------------------------
# Choose between "table" and "cards"
contact-layout: "cards"

# General Site settings
# ------------------------------------------------------------------------------
title: The Title
name: Acme Ltd
tagline: This is a really awesome tagline for the business
call-to-action: Contact Us Today # this will be used to introduce buttons

# Email - leave blank if not required
email: david@carawebs.com

# Facebook link
facebook: https://www.facebook.com/

# Twitter Link
#twitter: https://twitter.com

# Number to display - shown on the button
phone: 087 123 4567

# Number to call - used for a link, use format +35361... no spaces
phonenumber: +353871234567

# Short site description
description: "Short And Simple Site Description"

# Info for the Address Block - leave any variable blank and it won't be added
# ------------------------------------------------------------------------------
# Business Name
business-name: Acme Ltd
# Address Line 1:
address-line-1: Address 1
# Address Line 2:
#address-line-2:
# Address Town:
address-town: Town
# Address County:
address-county: Co. County
# Address Country:
address-country: Ireland
# VAT Number:
VATNo:
# Company Number
CoNo: 98765
# Additional Number - set the name, then the number
#additionalKey: RDI Number
#additionalValue: 123

# Personnel Information
# ------------------------------------------------------------------------------
# This is held in _data/people.json

# EDITORS: DO NOT EDIT BELOW THIS LINE
# DEV ONLY!!!
# ------------------------------------------------------------------------------
#baseurl: "http://localhost:9000/"
baseurl: "/sitename"

# For staging site
url: "http://yourdomain.com/sitename"
exclude: [node_modules, assets/original-images, Gruntfile.js, HINTGruntfile.js, bower.json, package.json, readme.md]

# Build settings
markdown: kramdown

#include: [bower_components/font-awesome/fonts]
permalink: pretty
version: 1
