- title: "Service 1"
  description: "Description of service 1"
  url: "/service-1/"
  image: "assets/images/medium-images/service-1.jpg"

- title: "Service 2"
  description: "Description of service 2"
  url: "/service-2/"
  image: "assets/images/medium-images/service-2.jpg"
